# Generated by Django 2.2.4 on 2020-12-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0005_auto_20201224_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='numberOfItem',
        ),
    ]
